### ISSUE TITLE
Provide better error handling methods

### ISSUE THREAD

**Issue by ananthanandanan** [Aniketh01/NaWaB#12]

**Comment by Aniketh01** [comment]
@ananthanandanan , @iammarco11 Please do more research on how to add better error handling into this project, handling tweepy error codes, python3 based error handling and other stuff. Make sure the discussion on this happens here as to keep note no what all have to be fixed and what's not.

**Comment by Aniketh01** [comment]
This is how proper logging should be handled: https://docs.python.org/2.3/lib/node304.html
