### ISSUE TITLE
Blacklist the bot account itself

### ISSUE THREAD

**Issue by Aniketh01** [Aniketh01/NaWaB#17]
I did notice that the bot is retweeting the same tweet again from the retweet of the bot. Blacklisting the bot twitter account would reduce the duplication or retweets coming from the bot itself.

**Comment by ananthanandanan** [comment]
Should this be done in another branch?

**Comment by Aniketh01** [comment]
All the code that can be merged should go through as a pull request, a WIP is more than welcome :)
Since you have access to the repo, you can create branches within the repo and push in your changes and easily spawn up a pull request as well. I think this is more convenient that fork + pull request. And also convenient for the team to check to do a git pull and get all your changes to test our and review :)

**Comment by ananthanandanan** [comment]
duly noted :)

**Comment by iammarco11** [comment]
@Aniketh01 can this issue be closed now?
#60 solves this
