### ISSUE TITLE
Telegram bot: A button for admins to integrate with the bot on manually retweeting a choosen tweet.

### ISSUE THREAD

**Issue by Aniketh01** [Aniketh01/NaWaB#24]

**Comment by iammarco11** [comment]
Is this issue relevant anymore, as we are not sending the message to the telegram channel.

**Comment by Aniketh01** [comment]
So what is the difference? Anyone can spawn up the bot as well. But not all people should have the right to ask the bot to retweet. That should be specifically for the admins/developers of this project alone.

**Comment by Aniketh01** [comment]
This is still a valid issue to be fixed.

**Comment by Aniketh01** [comment]
Fixed with: https://github.com/Aniketh01/NaWaB/commit/a25e7a0b47c088444034b76484c74d2b7bfe6d36
