### ISSUE TITLE
Inaccurate logging of the retweets; tweets are logged late after the next retweet is done

### ISSUE THREAD

**Issue by iammarco11** [Aniketh01/NaWaB#9]
Hey,

So there is an issue which I encountered after running the script, as 2 tweets were retweeted, while it logged only one of those tweets in the file.

**Comment by Aniketh01** [comment]
Can you provide the logs as well?

**Comment by iammarco11** [comment]
this issue can be closed as now we have a retweet button

**Comment by Aniketh01** [comment]
@iammarco11 The twitter function is still retweeting
